In [1]:
# Matrix multiplication

import numpy as np

def matrix_multiplication(A, B):
    return np.dot(A, B)

W1 = np.array([ 
                [0.1, -0.2,0.3,0.4],
                [0.5, -0.3,0.1,-0.2],
                [0.4, 0.2,-0.5,0.3]
            ])

b1 = np.array([[0.1], [-0.1], [0.05]])

W2 = np.array([
                [-0.3, 0.2, 0.1],
                [0.4, -0.5, 0.3]
             ])
                
b2 = np.array([[0.05], [-0.05]])

X = np.array([[1.0], [-1.0], [0.5], [2.0]])

def ReLU(x):
    return np.maximum(0, x)

def sinx(x):
    return np.sin(x)

def H(x):
    return sinx(x)+ReLU(x)


In [2]:
Z1 = matrix_multiplication(W1, X) + b1
H1 = H(Z1)
Z2 = matrix_multiplication(W2, H1) + b2

Z1, H1, Z2



(array([[1.35],
        [0.35],
        [0.6 ]]),
 array([[2.32572336],
        [0.69289781],
        [1.16464247]]),
 array([[-0.3926732 ],
        [ 0.88323318]]))